import Link from 'next/link'
import './globals.css'
import styles from "./layout.module.css"
import utilStyles from "./utils.module.css"
import Image from 'next/image'

export const metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const name = "Adil Nadeem";
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <header className={styles.header}>
            <Link href="/">
              <Image
                src="/images/profile.jpg" // Route of the image file
                height={144} // Desired size with correct aspect ratio
                width={144} // Desired size with correct aspect ratio
                alt="Your Name"
              />
            </Link>
            <h1 className={utilStyles.heading2Xl}>{name}</h1>
        {children}
          </header>
        </div>
      </body>
    </html>
  )

}
